### PR TITLE
Feat: configurable timeout for forge

### PR DESCRIPTION
**Pull request by mgkimsal**
Forge deployments were taking more than the default 30 seconds.  Added configurable parameter, defaulting to 180 seconds (3 minutes).

### CODE REVIEW

**Comment by mehrancodes** [comment]
We may also need to add the `setTimeout` to the given env key while creating the forge site.

```php
$forge->setTimeout(120)->createSite(SERVER_ID, [SITE_PARAMETERS]);
```

**Comment by mgkimsal** [comment]
@mehrancodes  - I'd missed the actual timeout line in ForgeService.  Added in PR.

**Comment by mgkimsal** [comment]
For what it's worth, I was able to get this to 'run' successfully from a local state with this patch in place without timing out, but can't easily test from external github action because... the whole thing times out.  If this could be merged and released, that would give me a much easier time trialing this going forward.

**Review by mehrancodes — APPROVED** [review]
Let's Merge! 👨🏻‍💻⚡️

**Comment by mehrancodes** [comment]
@mgkimsal Thanks for the great idea 🙌

**Comment by mgkimsal** [comment]
@mehrancodes - thanks for your openness and quick turnaround!

Will you be making a new release today or tomorrow?

**Pull request merged**
